[package]
name = "webfx-tokio"
version = "1.0.0"

[dependencies]
futures = "0.1.11"
num_cpus = "1.2.1"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
tokio-core = "0.1"
tokio-minihttp = { git = "https://github.com/tokio-rs/tokio-minihttp" }
tokio-proto = "0.1"
tokio-service = "0.1"
